[DEFAULT]
# All sections below are required unless otherwise specified.
# See https://github.com/fastai/nbdev/blob/master/settings.ini for examples.

### Python library ###
repo = sleepjepa
lib_name = %(repo)s
version = 0.0.1
min_python = 3.10
license = apache2
black_formatting = False

### nbdev ###
doc_path = _docs
lib_path = sleepjepa
nbs_path = nbs
recursive = True
tst_flags = notest
put_version_in_init = True

### Docs ###
branch = main
custom_sidebar = False
doc_host = https://%(user)s.github.io
doc_baseurl = /%(repo)s
git_url = https://github.com/%(user)s/%(repo)s
title = %(lib_name)s

### PyPI ###
audience = Developers
author = benmfox
author_email = benmfox@me.com
copyright = 2026 onwards, %(author)s
description = SleepJEPA: Learning the latent world of sleep
keywords = foundation model JEPA sleep deep learning pytorch
language = English
status = 3
user = benmfox

### Optional ###
requirements = execnb==0.1.12 fastcore<2 setuptools>=64.0,<75.0 wandb==0.19.2 scikit-learn ipykernel pyedflib mne edfio nbdev==2.4.14 tqdm scipy zarr dask torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 torchmetrics==1.6.1 seaborn matplotlib pyyaml numpy pandas plotly==5.15.0 lightning==2.5.0 torchsurv==0.1.4 rotary-embedding-torch scikit-survival zclip pytz transformers==4.51.3
# dev_requirements = 
# console_scripts =