"""Because this will help"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_augmentations.ipynb.

# %% auto #0
__all__ = ['create_patch', 'mask_patches_simple', 'unpatch', 'remove_values', 'jitter_augmentation', 'shuffle_dim',
           'reverse_sequence', 'channel_masking', 'random_crop', 'MixupCallbackClassification', 'TransformsCallback',
           'VariableChannelInput']

# %% ../nbs/06_augmentations.ipynb #c34d18b9
import torch, torch.nn.functional as F
from lightning.pytorch.callbacks import Callback
from torch.distributions.beta import Beta
from torchvision.transforms import RandomCrop


# %% ../nbs/06_augmentations.ipynb #4825f3dd
def create_patch(xb, patch_len, stride, constant_pad=False, constant_pad_value=0):
    """
    xb: [bs x n_vars x seq_len]
    out: [bs x num_patch x n_vars x patch_len]
    """
    if xb.dim() == 2:
        xb = xb.unsqueeze(0)
    if xb.is_nested:
        x_list = list(xb.unbind())
        seq_lens = [x.shape[-1] for x in x_list]
        for i, seq_len in enumerate(seq_lens):
            if constant_pad:
                if ((seq_len-patch_len) % stride != 0):
                    x_list[i] = F.pad(x_list[i], (0, stride), 'constant', value=constant_pad_value)
            x_list[i] = x_list[i].permute(1,0)
            x_list[i] = x_list[i].unfold(dimension=0, size=patch_len, step=stride)
        xb = torch.nested.as_nested_tensor(x_list, layout=torch.jagged)
    else:
        if constant_pad:
            seq_len = xb.shape[-1]
            # seq_len > patch_len and stride <= seq_len - patch_len
            if ((seq_len-patch_len) % stride != 0):
                # only pad if remainder
                xb = F.pad(xb, (0, stride), 'constant', value=constant_pad_value) # pad at the end with value
        xb = xb.permute(0,2,1) # xb: [bs x tgt_len x nvars]
        xb = xb.unfold(dimension=1, size=patch_len, step=stride) # xb: [bs x num_patch x n_vars x patch_len]
    return xb

# %% ../nbs/06_augmentations.ipynb #6f277ada
def mask_patches_simple(xb, mask_ratio):
    """
    Function that masks patches using fixed ratio approach similar to random_masking
    
    xb: [bs x patch_num x n_vars x patch_len] or nested tensor
    Returns:
        x_masked: masked tensor with same shape as input
        mask: binary mask where 1 indicates masked positions (bs x patch_num x n_vars)
    """
    if xb.dim() == 3:
        xb = xb.unsqueeze(0)
    x = xb.clone()
    
    if x.is_nested:
        x_list = list(x.unbind())
        for i, x_i in enumerate(x_list):
            # Get dimensions for this tensor in the nested set
            L, nvars, D = x_i.shape
            len_keep = int(L * (1 - mask_ratio))
            
            # Generate random noise for selecting which patches to keep/mask
            noise = torch.rand(L, nvars, device=xb.device)
            # Sort noise to determine keep/mask ordering (smallest values are kept)
            ids_shuffle = torch.argsort(noise, dim=0)  # sort noise for each variable
            # Create restore indices to return to original order later
            ids_restore = torch.argsort(ids_shuffle, dim=0)
            
            # Select patches to keep (those with smallest noise values)
            ids_keep = ids_shuffle[:len_keep]
            # Gather kept patches and their corresponding values
            x_kept = torch.gather(x_i, dim=0, index=ids_keep.unsqueeze(-1).repeat(1, 1, D))
            
            # Create and combine with zeros for masked positions
            # Create tensor of zeros for masked positions
            x_removed = torch.zeros(L - len_keep, nvars, D, device=xb.device).detach()
            # Combine kept and masked patches
            x_ = torch.cat([x_kept, x_removed], dim=0)
            
            # Restore original patch ordering
            x_list[i] = torch.gather(x_, dim=0, index=ids_restore.unsqueeze(-1).repeat(1, 1, D))
            
        x_masked = torch.nested.as_nested_tensor(x_list, layout=torch.jagged)
    else:
        bs, L, nvars, D = x.shape
        len_keep = int(L * (1 - mask_ratio))
        
        # Generate noise and sort for masking
        noise = torch.rand(bs, L, nvars, device=xb.device)
        ids_shuffle = torch.argsort(noise, dim=1)
        ids_restore = torch.argsort(ids_shuffle, dim=1)
        
        # Keep the first subset
        ids_keep = ids_shuffle[:, :len_keep]
        x_kept = torch.gather(x, dim=1, index=ids_keep.unsqueeze(-1).repeat(1, 1, 1, D))
        
        # Create and combine with zeros for masked positions
        x_removed = torch.zeros(bs, L - len_keep, nvars, D, device=xb.device).detach()
        x_ = torch.cat([x_kept, x_removed], dim=1)
        
        # Restore original order
        x_masked = torch.gather(x_, dim=1, index=ids_restore.unsqueeze(-1).repeat(1, 1, 1, D))
    
    return x_masked

# %% ../nbs/06_augmentations.ipynb #0efa1688
def unpatch(x, seq_len, remove_padding=True):
    """
    x: [bs/None x patch_num x n_vars x patch_len]
    returns x: [bs x n_vars x seq_len]
    """
    if x.dim() == 3:
        x = x.transpose(0,1)
    else:
        x = x.transpose(1,2)
    if x.is_nested:
        x_list = list(x.unbind())
        for i in range(len(x_list)):
            x_list[i] = x_list[i].flatten(start_dim=1)
            if remove_padding:
                x_list[i] = x_list[i][..., :seq_len[i]]
        x = torch.nested.as_nested_tensor(x_list, layout=torch.jagged)
    else:
        x = x.flatten(start_dim=-2, end_dim=-1)
        if remove_padding:
            x = x[...,:seq_len]
    return x

# %% ../nbs/06_augmentations.ipynb #29cc8322
def remove_values(x, mask_ratio):
    mask = torch.rand(x.shape, device=x.device) > mask_ratio # maskout_ratio are False, note that this is per channel masking
    x = x*mask
    return x

def jitter_augmentation(x, mask_ratio=0.05, jitter_ratio=0.05, p=1):
    prob = torch.rand(1) < p
    if not prob:
        return x
    if x.is_nested:
        out_tensors = []
        for x_i in x:
            max_amplitude = x_i.abs().max()  # Use absolute max for amplitude scale
            zero_mask = torch.rand(x_i.shape, device=x.device) > mask_ratio
            jitter_mask = torch.rand(x_i.shape, device=x.device) > (1-jitter_ratio)
            jitter_values = torch.randn(x_i.shape, device=x.device) * max_amplitude * 0.1  # Normal distribution centered at 0 times 10% of max amplitude
            
            out_tensors.append((x_i*zero_mask + jitter_mask*jitter_values).transpose(0,1))
        x = torch.nested.as_nested_tensor(out_tensors, layout=torch.jagged)
        x = x.transpose(1,2)
    else:
        x = x.clone()  
        max_amplitude = x.abs().max()  # Use absolute max for amplitude scale

        zero_mask = torch.rand(x.shape, device=x.device) > mask_ratio
        jitter_mask = torch.rand(x.shape, device=x.device) > (1-jitter_ratio)
        jitter_values = torch.randn(x.shape, device=x.device) * max_amplitude * 0.1  # Normal distribution centered at 0 times 10% of max amplitude
        
        x = x*zero_mask + jitter_mask*jitter_values
    return x

# %% ../nbs/06_augmentations.ipynb #947d5072
def shuffle_dim(x, dim=1, p=0.5):
    """
    shuffles a dimension randomly along dim
    x: [bs x n channels x n patches x patch len]
    """
    if torch.rand(1, device=x.device) > (1-p):
        idx = torch.randperm(x.size(dim), device=x.device)
        return torch.index_select(x, dim, idx)
    else:
        return x


# %% ../nbs/06_augmentations.ipynb #c885cc81
def reverse_sequence(x, seq_dim=(-1,), p=0.5):
    if torch.rand(1, device=x.device) > (1-p):
        return torch.flip(x, dims=seq_dim)
    else:
        return x

# %% ../nbs/06_augmentations.ipynb #90aaba67
def channel_masking(x, dim=1, p=0.5, specific_channels=None):
    """
    Masks up to n channels - 1 randomly of x or specific channels if provided
    """
    if specific_channels is not None:
        specific_channels = [specific_channels] if isinstance(specific_channels, int) else specific_channels
        idx = torch.tensor(specific_channels, device=x.device)
        if torch.rand(1, device=x.device) > (1-p):
            if x.is_nested:
                x_list = list(x.unbind())
                for i, x_i in enumerate(x_list):
                    mask = torch.ones_like(x_i, device=x.device) # mask of ones
                    mask[idx] = 0 # set the mask to 0 for the channels to mask
                    x_list[i] = (x_i * mask).transpose(0,1) # apply the mask
                x = torch.nested.as_nested_tensor(x_list, layout=torch.jagged)
                x = x.transpose(1,2)
            else:
                mask = torch.ones_like(x, device=x.device) # mask of ones
                mask[:,idx] = 0 # set the mask to 0 for the channels to mask
                x = x * mask # apply the mask
    else:
        if torch.rand(1, device=x.device) > (1-p):
            if x.is_nested:
                x_list = list(x.unbind())
                for i, x_i in enumerate(x_list):
                    n_channels_to_mask = torch.randint(1, x_i.size(dim-1), (1,), device=x.device)
                    mask = torch.ones_like(x_i, device=x.device) # mask of ones
                    idx = torch.randperm(x_i.size(dim-1), device=x.device)[:n_channels_to_mask] # get n_channels_to_mask random indices
                    mask[:, idx] = 0 # set the mask to 0 for the channels to mask
                    x_list[i] = (x_i * mask).transpose(0,1) # apply the mask
                x = torch.nested.as_nested_tensor(x_list, layout=torch.jagged)
                x = x.transpose(1,2)
            else:
                n_channels_to_mask = torch.randint(1, x.size(dim), (1,), device=x.device)
                mask = torch.ones_like(x, device=x.device) # mask of ones
                idx = torch.randperm(x.size(dim), device=x.device)[:n_channels_to_mask] # get n_channels_to_mask random indices
                mask[:,idx] = 0 # set the mask to 0 for the channels to mask
                x = x * mask # apply the mask
    return x

# %% ../nbs/06_augmentations.ipynb #f8c01beb
def random_crop(x, c_in, min_len, p=0.5):
        """
        Args:
            x: Either a regular tensor [n_channels x seq_len] 
               or a nested tensor with variable lengths
        Returns:
            Cropped version of input with random length
        """
        prob = torch.rand(1) < p
        if not prob:
             return x
        if x.is_nested:
            # Handle batch of variable length sequences
            cropped_tensors = []
            for x_i in x:
                seq_len = x_i.size(-1)
                if seq_len <= min_len:
                    cropped_tensors.append(x_i)
                    continue
                crop_length = torch.randint(min_len, seq_len, size=(1,)).item()
                crop = RandomCrop(size=(c_in, crop_length)) # size is desired output size
                cropped_tensors.append(crop(x_i).transpose(0,1))
            x = torch.nested.as_nested_tensor(cropped_tensors, layout=torch.jagged)
            x = x.transpose(1,2)
            return x
        else:
            # Handle single sequence
            seq_len = x.size(-1)
            if seq_len <= min_len:
                return x
            crop_length = torch.randint(min_len, seq_len, size=(1,)).item()
            crop = RandomCrop(size=(c_in, crop_length)) # size is desired output size
            return crop(x)


# %% ../nbs/06_augmentations.ipynb #460bc268
class MixupCallbackClassification(object):
    """
    Mixup for 1D data (e.g., time-series).

    This callback applies Mixup to the training data, blending both the input data and the labels.

    See tsai implementation here: https://github.com/timeseriesAI/tsai/blob/bdff96cc8c4c8ea55bc20d7cffd6a72e402f4cb2/tsai/data/mixed_augmentation.py#L43

    Note that this creates non-integer labels/soft labels. Loss functions should be able to handle this.
    """
    def __init__(self, 
                 num_classes,
                 mixup_alpha=0.4, # alpha parameter for the beta distribution
                 ignore_index=-100 # ignore index
                 ):
        super().__init__()
        self.distrib = Beta(mixup_alpha, mixup_alpha)
        self.mixup_alpha = mixup_alpha
        self.ignore_index = ignore_index
        self.num_classes = num_classes

    def __call__(self, batch):
        x, y = batch  # x: [batch_size, channels, time_steps], y: [batch_size, time_steps]
        bs, c_in, _ = x.shape
        was_nested = x.is_nested
        if x.is_nested:
            max_len = max(x.size(-1) for x in x.unbind())
            og_x_seq_len = [i.size(-1) for i in x.unbind()]
            x = x.to_padded_tensor(padding=0, output_size=(bs, c_in, max_len))

        # Sample lambda from a beta distribution
        lam = self.distrib.sample((x.size(0), )).to(x.device) # [bs]
        # our mixing coefficient is always ≥ 0.5
        lam = torch.max(lam, 1 - lam)
        lam_x = lam.view(-1, 1, 1)  # for input shape [bs, channels, seq_len]
        lam_y = lam.view(-1, 1)

        # Shuffle the batch
        indices = torch.randperm(x.size(0), device=x.device)
    
        x_shuffled = x[indices]
        y_shuffled = y[indices]

        # create ignore masks
        ignore_mask = (y == self.ignore_index)
        ignore_mask_shuffled = (y_shuffled == self.ignore_index)
        combined_ignore_mask = torch.logical_or(ignore_mask, ignore_mask_shuffled)

        y_clean = torch.where(ignore_mask, torch.zeros_like(y), y).long()
        y_shuffled_clean = torch.where(ignore_mask_shuffled, torch.zeros_like(y_shuffled), y_shuffled).long()
        # Create one-hot encodings
        if y.ndim == 1:
            y_onehot = F.one_hot(y_clean, num_classes=self.num_classes).float()
            y_shuffled_onehot = F.one_hot(y_shuffled_clean, num_classes=self.num_classes).float()
            ignore_mask = ignore_mask.unsqueeze(-1)
            ignore_mask_shuffled = ignore_mask_shuffled.unsqueeze(-1)
            combined_ignore_mask = combined_ignore_mask.unsqueeze(-1)
        else:
            y_onehot = y_clean.float()
            y_shuffled_onehot = y_shuffled_clean.float()
        # Zero out the one-hot vectors for ignored indices
        y_onehot = torch.where(ignore_mask, torch.zeros_like(y_onehot), y_onehot)
        y_shuffled_onehot = torch.where(ignore_mask_shuffled, torch.zeros_like(y_shuffled_onehot), y_shuffled_onehot)
        # Mixup the inputs and labels
        x_mixed = torch.lerp(x, x_shuffled, lam_x) # x = x_shuffled + lam * (x - x_shuffled)
        y_mixed = torch.lerp(y_onehot, y_shuffled_onehot, lam_y) # y = y_shuffled + lam * (y - y_shuffled)

        # finally assign all probabilities with a -100 mixing to 0
        y_mixed = torch.where(combined_ignore_mask, torch.zeros_like(y_mixed), y_mixed)
        # # add back in the ignore index where it was mixed with other labels
        if was_nested:
            x_list = []
            for i in range(bs):
                x_list.append(x_mixed[i, :, :og_x_seq_len[i]].transpose(0,1))
            x_mixed = torch.nested.as_nested_tensor(x_list, layout=torch.jagged)
            x_mixed = x_mixed.transpose(1,2)
        return (x_mixed, y_mixed)

# %% ../nbs/06_augmentations.ipynb #3454ae85
class TransformsCallback(object):
    """
    Applies a series of transforms to the input data, on train_batch_start.
    """
    def __init__(self, transforms):
        self.transforms = transforms
    def __call__(self, batch):
        if len(batch) == 3:
            x, y, time = batch  # x: [batch_size, channels, time_steps], y: [batch_size, time_steps]
        else:
            x, y = batch
        for transform in self.transforms:
            x = transform(x)
        if len(batch) == 3:
            return (x,y,time)
        else:
            return (x,y)

# %% ../nbs/06_augmentations.ipynb #fe9ae66c
class VariableChannelInput(object):
    """
    Randomly adds 0 channels at correct index to the input data to match the number of channels expected by the self supervised model.
    """
    def __init__(self, indexes_to_add_channels, n_channels_expected, channel_dim=1):
        super().__init__()
        if not isinstance(indexes_to_add_channels, list) and not isinstance(indexes_to_add_channels, tuple):
            raise ValueError("indexes_to_add_channels must be a list or tuple")
        if not all(isinstance(i, int) for i in indexes_to_add_channels):
            raise ValueError("indexes_to_add_channels must be a list or tuple of integers")
        self.indexes_to_add_channels = indexes_to_add_channels
        self.n_channels_expected = n_channels_expected
        self.channel_dim = channel_dim
    
    def _modify_batch(self, x):
        assert x.shape[self.channel_dim] + len(self.indexes_to_add_channels) == self.n_channels_expected, f"The number of channels expected ({self.n_channels_expected}) by the model must match the number of channels in the input data ({x.shape[self.channel_dim]}) plus the number of channels to add ({len(self.indexes_to_add_channels)})"
        # append zeros to the channels at the end of the input data

        if x.is_nested:
            x_list = list(x.unbind())
            for i, x_i in enumerate(x_list):
                x_list[i] = torch.cat([x_i, torch.zeros(len(self.indexes_to_add_channels), x_i.shape[1], device=x.device)], dim=self.channel_dim-1)
            x = torch.nested.as_nested_tensor(x_list, layout=torch.jagged)
        else:
            x = torch.cat([x, torch.zeros(x.shape[0], len(self.indexes_to_add_channels), x.shape[2], device=x.device)], dim=self.channel_dim)
        # reindex to match the correct channel order
        new_indices = list(range(self.n_channels_expected))
        # find the added 0 indices and their new indices
        index_to_add_dict = dict(zip(new_indices[-len(self.indexes_to_add_channels):], self.indexes_to_add_channels))
        for old_idx, new_idx in index_to_add_dict.items():
            new_indices.insert(new_idx, new_indices.pop(old_idx))
        if x.is_nested:
            x_list = list(x.unbind())
            for i, x_i in enumerate(x_list):
                x_list[i] = torch.index_select(x_i, dim=self.channel_dim-1, index=torch.tensor(new_indices, device=x.device))
            x = torch.nested.as_nested_tensor(x_list, layout=torch.jagged)
        else:
            x = torch.index_select(x, dim=self.channel_dim, index=torch.tensor(new_indices, device=x.device))
        return x
    
    def reverse(self, x):
        # reverse the channel addition
        if x.is_nested:
            x_list = list(x.unbind())
            for i, x_i in enumerate(x_list):
                x_list[i] = torch.index_select(x_i, dim=self.channel_dim-1, index=torch.tensor([i for i in range(x_i.shape[self.channel_dim-1]) if i not in self.indexes_to_add_channels], device=x.device))
            x = torch.nested.as_nested_tensor(x_list, layout=torch.jagged)
        else:
            x = torch.index_select(x, dim=self.channel_dim, index=torch.tensor([i for i in range(x.shape[self.channel_dim]) if i not in self.indexes_to_add_channels], device=x.device))
        return x
        
    def __call__(self, x):
        return self._modify_batch(x)
