"""Imagine a word is an interval of time series data..."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/12_tokenizers.ipynb.

# %% auto #0
__all__ = ['TS_Tokenizer', 'TS_Tokenizer_Complex', 'InceptionTokenizer', 'PatchEncoder']

# %% ../nbs/12_tokenizers.ipynb #941bdd24
import torch, torch.nn.functional as F, torch.nn as nn
from .layers import *

# %% ../nbs/12_tokenizers.ipynb #bd4f27db
class TS_Tokenizer(nn.Module):
    """
    Tokenizer class based on a Conv1D that handles both nested and regular tensors.
    ---
        c_in (int): Number of input channels
        patch_size (int): Size of each patch/kernel
        d_model (int): Output embedding dimension
    """
    def __init__(self, c_in, patch_size, d_model, patch_stride=None, shared_embedding=True, variable_channel_callback=None):
        super().__init__()
        self.c_in = c_in
        self.d_model = d_model
        self.patch_size = patch_size
        self.patch_stride = patch_stride if patch_stride is not None else patch_size
        self.shared_embedding = shared_embedding
        if not shared_embedding:
            assert d_model % c_in == 0, f"d_model ({d_model}) must be divisible by c_in ({c_in})"
        self.proj = nn.Conv1d(
            in_channels=c_in,
            out_channels=d_model, # if shared embedding, then d_model is the output dimension
            kernel_size=self.patch_size,
            stride=self.patch_stride,
            padding=0,
            groups=c_in if not shared_embedding else 1 # added to handle multiple channels / keep them separate
        )

        self.variable_channel_callback = variable_channel_callback

    def forward(self, x):
        if self.variable_channel_callback is not None:
            x = self.variable_channel_callback(x)
        was_nested = x.is_nested
        
        if was_nested:
            # Store original sequence lengths for later trimming
            seq_lens = [seq.size(-1) for seq in x]
            
            # Convert to padded tensor
            x = x.to_padded_tensor(0.)
        
        # Process everything as regular tensor
        bs, C, seq_len = x.shape
        if ((seq_len - self.patch_size) % self.patch_stride != 0):
            pad_amount = self.patch_stride - ((seq_len - self.patch_size) % self.patch_stride)
            x = F.pad(x, (0, pad_amount), 'constant', value=0.)
        
        x = self.proj(x)  # [batch_size, d_model, num_patches]
        
        if not self.shared_embedding:
            x = x.reshape(bs, self.c_in, self.d_model // self.c_in, -1)
            x = x.permute(0, 3, 1, 2)  # [batch_size, num_patches, n_vars, d_model//c_in]
        else:
            x = x.transpose(1, 2)  # [batch_size, num_patches, d_model]
        
        if was_nested:
            # Calculate actual num_patches for each sequence
            num_patches_list = []
            for seq_len in seq_lens:
                n_patches = (seq_len - self.patch_size) // self.patch_stride + 1
                if ((seq_len - self.patch_size) % self.patch_stride != 0):
                    n_patches += 1
                num_patches_list.append(n_patches)
            
            # Trim to actual lengths and convert back to nested
            out_tensors = [x[i, :num_patches_list[i]] for i in range(bs)]
            x = torch.nested.as_nested_tensor(out_tensors, layout=torch.jagged)
        return x

class TS_Tokenizer_Complex(nn.Module):
    """
    Time series 2D convolutional Embedding
    """
    def __init__(
        self,
        c_in,
        patch_size,
        d_model,
        constant_pad_value=0.
    ):
        super().__init__()
        self.patch_size = patch_size
        self.constant_pad_value = constant_pad_value
        #self.simple_conv = nn.Conv1d(c_in, d_model, kernel_size=patch_size, stride=patch_size)
        self.emb_1 = nn.Conv2d(1, d_model*4, kernel_size=[1, patch_size], stride=[1, patch_size])
        self.emb_2 = nn.Conv2d(d_model*4, d_model, kernel_size=[c_in, 1])
   
    def forward(self, x):
        """
        Input: [bs x n channels x seq_len]
        Out:  [bs x num_patch x d_model]
        """
        was_nested = x.is_nested
        if was_nested:
            n_patches = []
            for i in x.unbind():
                # calculate expected number of patches for subsetting after conv
                np = int((max(i.size(-1), self.patch_size)-self.patch_size) // self.patch_size + 1)
                if ((i.size(-1)-self.patch_size) % self.patch_size != 0):
                    np += 1
                n_patches.append(np)
            # convert to padded
            x = x.to_padded_tensor(0.)
        bs, C, seq_len = x.shape
        #x = self.simple_conv(x).transpose(1, 2)
        if ((seq_len-self.patch_size) % self.patch_size != 0):
            # only pad if remainder
            x = F.pad(x, (0, self.patch_size), 'constant', value=self.constant_pad_value) # pad at the end with value
        x = x.unsqueeze(1)
        x = self.emb_1(x) # [bs x d_model*4 x n channels x n patches]
        x = self.emb_2(x) # [bs x d_model x 1 x n patches]
        x = x.transpose(1, 3) 
        if was_nested:
            out_tensors = [x[i, :seq_len, :, :] for i, seq_len in enumerate(n_patches)]
            x = torch.nested.as_nested_tensor(out_tensors, layout=torch.jagged)
            #x = x.transpose(1,2)
        return x.squeeze(2)
    
class InceptionTokenizer(nn.Module):
    def __init__(self, 
                 c_in, # the number of input channels
                 patch_size, # the length of the patches (either stft or interval length)
                 d_model, # the dimension of the initial linear layers for inputting patches into transformer
                 patch_stride=None, # the stride of the patches
                 shared_embedding=True,
                 **tokenizer_kwargs
                 ):
        super().__init__()
        self.n_vars = c_in
        self.patch_size = patch_size
        self.patch_stride = patch_stride if patch_stride is not None else patch_size
        self.d_model = d_model
        self.shared_embedding = shared_embedding
        self.inception = InceptionBlock(in_channels=c_in, groups=c_in if not shared_embedding else 1, **tokenizer_kwargs)
        self.inception_out = self.inception.bottleneck_channels * 4
        if not shared_embedding:
            assert d_model % c_in == 0, f"d_model ({d_model}) must be divisible by c_in ({c_in})"

        self.patch = nn.Conv1d(
            in_channels=self.inception_out,
            out_channels=d_model,
            kernel_size=self.patch_size,
            stride=self.patch_stride,
            padding=0,
            groups=self.n_vars if not shared_embedding else 1 # added to handle multiple channels / keep them separate
        )

    def forward(self, x):
        """
        input: x: tensor [bs x n channels x seq_len]
        returns: x: tensor [bs x num_patch x d_model]
        """
        was_nested = x.is_nested
        if was_nested:
            n_patches = []
            for i in x.unbind():
                # calculate expected number of patches for subsetting after conv
                num_p = int((max(i.size(-1), self.patch_size)-self.patch_size) // self.patch_stride + 1)
                if ((i.size(-1)-self.patch_size) % self.patch_stride != 0):
                    num_p += 1
                n_patches.append(num_p)
            # convert to padded
            x = x.to_padded_tensor(0.)
        bs, C, seq_len = x.shape
        if ((seq_len-self.patch_size) % self.patch_size != 0):
            # only pad if remainder
            x = F.pad(x, (0, self.patch_size), 'constant', value=0.) # pad at the end with value
        x = self.inception(x) # [bs x d_model * n_vars (if not shared embedding) else d_model x seq_len]
        x = self.patch(x)
        if not self.shared_embedding:
            x = x.reshape(bs, self.n_vars, self.d_model // self.n_vars if not self.shared_embedding else self.d_model, -1)
            x = x.permute(0, 3, 1, 2)
        else:
            x = x.transpose(1, 2) # [bs x num_patch x num_vars xd_model]
        if was_nested:
            out_tensors = [x[i, :seq_len, ...] for i, seq_len in enumerate(n_patches)]
            x = torch.nested.as_nested_tensor(out_tensors, layout=torch.jagged)
        return x


# %% ../nbs/12_tokenizers.ipynb #db2ef7f1
class PatchEncoder(nn.Module):
    def __init__(self, 
                 c_in, # the number of input channels
                 patch_len, # the length of the patches (either stft or interval length)
                 d_model, # the dimension of the initial linear layers for inputting patches into transformer
                 shared_embedding, # indicator of whether to project each channel individually or together
                 ):
        super().__init__()

        self.shared_embedding = shared_embedding
        self.n_vars = c_in
        self.patch_len = patch_len
        self.d_model = d_model

        # Input encoding: projection of feature vectors onto a d-dim vector space
        ## note that this could be an MLP too, if you want
        if not shared_embedding:
            self.W_P = nn.ModuleList()
            for _ in range(self.n_vars): self.W_P.append(nn.Linear(patch_len, d_model))
        else:
            self.W_P = nn.Linear(patch_len, d_model)

    def forward(self, x):          
        """
        input: x: tensor [bs x num_patch x nvars x patch_len]
        returns: x: tensor [bs x num_patch x nvars x d_model]
        """
        # Input embedding
        if not self.shared_embedding:
            if x.is_nested:
                x_list = list(x.unbind())
                for i, x_i in enumerate(x_list):
                    x_out = []
                    for c in range(self.n_vars):
                        # Apply linear projection
                        x_out.append(self.W_P[c](x_i[:,c,:]))
                    x_list[i] = torch.stack(x_out, dim=1)
                x = torch.nested.as_nested_tensor(x_list, layout=torch.jagged)
            else:
                x_out = []
                for i in range(self.n_vars):
                    x_out.append(self.W_P[i](x[:,:,i,:]))
                x = torch.stack(x_out, dim=2)
        else:
            x = self.W_P(x) # x: [bs x num_patch x nvars x d_model]
        return x
