
run_config:
  model_type: "jepa"
  wandb_project: ""
  model_run: ""
  name: ""
  random_state: 126
  precision: "bf16-mixed"
  do_train: true
  test_checkpoint_path: null

paths:
  encoder_dir: ""
  pretrained_encoder_path: ""
  shhs_file_path: 'sleep_outcome_data/shhs__age.csv'
  wsc_file_path: 'sleep_outcome_data/wsc__age.csv'
  mesa_file_path: 'sleep_outcome_data/mesa__age.csv'
  mros_file_path: 'sleep_outcome_data/mros__age.csv'
  models_dir: ""
  ext_test_sets: ["MESA", "WSC"]
  dataset_filename: "age_SHHS_MROS__MESA_WSC"

dataset:
  nested: true
  frequency: 128
  patch_seconds: 3
  overlap: 0.
  max_seq_len_sec: 43200
  min_seq_len_sec: 21600
  include_partial_samples: true
  outcome_cols: ["age_s1"]
  normalize_signals: true
  constant_nan_tolerance: 1.

lp_head:
  mlp_ratio: 4.0
  depth: 1
  init_std: 0.02
  qkv_bias: true
  num_classes: 1
  complete_block: true
  per_channel: false

training:
  batch_size: 16
  epochs: 25
  n_gpus: 1
  num_workers: 14
  accumulate_grad_batches: 1
  val_check_interval: 0.5
  gradient_clip_val: 1
  use_gradient_clipping: true
  fine_tune: false
  use_lr_finder: false
  use_transforms: false
  
optimizer:
  learning_rate: 0.001
  weight_decay: 0.001
  use_weight_decay_scheduler: false
  final_weight_decay: 0.1
  optimizer_type: "AdamW"

scheduler:
  scheduler_type: "cosineannealingwarmrestarts"
  T_0: 5
  T_mult: 2
  eta_min: 0.000001