run_config:
  model_type: "demo_head"
  wandb_project: ""
  model_run: "1"
  name: ""
  random_state: 126
  precision: "bf16-mixed"
  do_train: true
  remove_channel_idxs: []
  test_checkpoint_path: null
  outcome_cols: ["hypertension_label"]

paths:
  encoder_dir: ""
  pretrained_encoder_path: ""

dataset:
  nested: true
  frequency: 128
  patch_seconds: 3
  overlap: 0.
  max_seq_len_sec: 43200
  min_seq_len_sec: 21600
  include_partial_samples: true
  normalize_signals: true
  constant_nan_tolerance: 1
  y_demographic_columns: ['age_s1', 'gender']
  demographic_embeddings: [9, 2]
  age_col: 'age_s1'
  age_mlp_hidden_size: 32
  demographic_dropout_rate: 0.5
  demographics_only: true

lp_head:
  mlp_ratio: 4.0
  depth: 2
  init_std: 0.02
  qkv_bias: true
  complete_block: true
  per_channel: false

training:
  discretize_time: true
  discrete_time_bins: 1.
  time_range_years: [0,15]
  evaluate_risk_years: null
  batch_size: 16
  epochs: 10
  n_gpus: 1
  num_workers: 14
  accumulate_grad_batches: 1
  val_check_interval: 0.5
  gradient_clip_val: 1
  use_gradient_clipping: true
  fine_tune: false

optimizer:
  learning_rate: 0.001
  weight_decay: 0.0001
  use_weight_decay_scheduler: false
  final_weight_decay: 0.1
  optimizer_type: "AdamW"


scheduler:
  scheduler_type: "cosineannealingwarmrestarts"
  T_0: 5
  T_mult: 2
  eta_min: 0.000001